apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: devlopment
spec:
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/jenkins-k8s-zdz/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
   name: demo
   namespace: devlopment
spec:
   selector:
     app: jenkins-demo
   type: NodePort
   ports:
   - port: 18888
     targetPort: 18888
     nodePort: 31889
